version: '3.8'
services:
  flask-app:
    build: .
    ports:
      - "9000:5000"
    env_file:
      - .env
    depends_on:
      - mongo-db

  mongo-db:
    container_name: mongo-db
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
